# Generated by Django 5.0.6 on 2024-06-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"], "verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "countries"},
        ),
    ]
